apiVersion: v1
kind: Pod
metadata:
  name: test2
  namespace: tt3
  labels:
    function: 'test2' # zum mappen des Services
spec:
  containers:
    - name: webserver2
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "200m"
          memory: "200M"
        requests:
          cpu: "200m"    
          memory: "200M"
---
apiVersion: v1
kind: Service
metadata:
  name: test2
  namespace: tt3
spec:
  type: LoadBalancer
  selector:
    function: 'test2' # ist das Label aus der Deployment YML
  ports:
    - protocol: TCP
      port: 30003
      targetPort: 80
