apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: tt3
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfs
    server: 192.168.60.133
