apiVersion: v1
kind: Pod
metadata:
  name: webfrontend
  labels:
    function: 'frontend' # zum mappen des Services
spec:
  containers:
    - name: webserver1
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webfrontend
spec:
  type: LoadBalancer
  selector:
    function: 'frontend' # ist das Label aus der Deployment YML
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
