apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restart-sa
  namespace: tt3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tt3
  name: pod-restart-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "delete"]  # Berechtigungen zum Abrufen und Löschen von Pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-restart-binding
  namespace: tt3
subjects:
- kind: ServiceAccount
  name: pod-restart-sa
  namespace: tt3
roleRef:
  kind: Role
  name: pod-restart-role
  apiGroup: rbac.authorization.k8s.io